<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */
function javelin_help($path, $arg){
    switch ($path) {
        case "admin/help#javelin":
            return '<p>' . t("Provides LinkedIn API peoplesearch tools.") . '</p>';
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function javelin_block_info() {
  $blocks['javelin_test_block'] = array(
    'info' => t('Javelin test block'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}